name: metroeye_flutter
description: "MetroEye"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.5.3
  uuid: ^4.5.3
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/

  uses-material-design: true

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/noto_sans_kr_bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans_kr_light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans_kr_medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_kr_regular.ttf
          weight: 400
